services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
        command: ["redis-server", "--protected-mode", "no"]
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build: 
            context: ./nginx
        ports:
            - "8081:80"
    api:
        build: ./server
        image: "docker.io/radhikav293/complex-api"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        build: ./client
        image: "docker.io/radhikav293/complex-client"
    worker:
        build: ./worker
        image: "docker.io/radhikav293/complex-worker"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
 